train_dataset_path: /home/elena/emcomm/emcomm_captions/checkpoints/winoground_100_eval_best_max_val_10_len_99th_epoch_orig/messages/coco_train_message_captions_3_distractors
val_dataset_path: /home/elena/emcomm/emcomm_captions/checkpoints/winoground_100_eval_best_max_val_10_len_99th_epoch_orig/messages/coco_val_message_captions_3_distractors
test_dataset_path: null
checkpoint_path: /home/elena/emcomm/emcomm_captions/checkpoints/winoground_100_eval_best_max_val_10_len_99th_epoch_orig/translation
test_only: false

model_type: transformer
src_vocab_size: 71

emb_dim: 256
hid_dim: 512
enc_num_layers: 2
dec_num_layers: 3
num_heads: 2
dropout: 0.0
pad_id: 70

batch_size: 512
lr_enc: 0.001
lr_dec: 0.001
num_epochs: 25
patience: 10
scheduler_patience: 20
scheduler_factor: 0.9

seed: 42

wandb_project: EmComm-Caption-Translator
wandb_name: winoground_99th_better_temp_tf_more_capacity
