checkpoint_save_path: './test_checkpoint_saving.pt'
vocab_size: 70
n_distractors: 5
n_epoch: 3
max_len: 100

sender_lr: 0.01
receiver_lr: 0.01
batch_size: 256

random_seed: 42
data_seed: 222

train_samples: 100
validation_samples: 100
test_samples: 100

evaluate: true
shuffle_train_data: false

load_data_path: /home/elena/emcomm/datasets/coco_npz/coco_full_train_val_152_resnet_5_distractors.npz

wandb: true
wandb_name: 3_distractors_check